### ISSUE TITLE
Audio link for vocabulary doesn't work

### ISSUE THREAD

**Issue by tbm** [longjiang/zerotohero-nuxt#2]
https://www.zerotohero.ca/en/sw/dictionary/wiktionary/8470

There's an audio link.  Wiktionary has an audio file.

But clicking it doesn't do anything.

I tried in Firefox and Chromium.

**Comment by longjiang** [comment]
Ahh... because it's a .flac file. I'm not sure if ogv supports it, I'll have to double-check. I'll turn off flac for now and direct users to forvo instead.

**Comment by longjiang** [comment]
Fixed with commit fc1c0662d977eada437bf4fc1afdf358a54112f6

**Comment by tbm** [comment]
If you look at the HTML of https://en.wiktionary.org/wiki/pete#Swahili you'll see that there are actually audio links for FLAC, Ogg and MP3.

Any chance you could get the MP3 or Ogg link from there and use that?
