### ISSUE TITLE
Certain smaller languages are difficult to click

### ISSUE THREAD

**Issue by DianaLunaXIV** [longjiang/zerotohero-nuxt#3]
This issue was noted in the video introducing the language map, but it's present elsewhere too. 

When trying to get to the Latin language (https://www.zerotohero.ca/en/la/), the map directs to the proper geographic area. In the case of Latin, it shares this area with Etruscan, and the link to the Etruscan language section covers Latin's link element to the extent that I could only expose the link to Latin in dev tools. 

A couple of possible solutions:

- Bringing the particular language into focus on the map when searched for (i.e. hiding other languages) would prevent link blocking.
- Going straight to the language page or providing a link to it within the search bar would allow direct access for visitors who know which language they're looking for, although it does not directly address the blocking link blocking issue.
- Introducing some sort of dynamic floating for languages on the map to prevent them from overlapping each other could be difficult, but it would prevent the undesired blocking and may even be aesthetically pleasing.

I don't have experience with Vue.js (although this project has inspired me to begin learning it 😄), or I would present this issue with a PR of some kind.

**Comment by longjiang** [comment]
Thank you so much for letting me know. Yes, I'm aware of this... I need to slightly shift languages lat and long so that they don't overlap.

**Comment by longjiang** [comment]
fc92cce fixes the issue with Latin and Etruscan. I'll come up with a more permanent solution for other possible overlapping languages soon.

**Comment by longjiang** [comment]
The language map is no longer the primary way to select languages.
