### ISSUE TITLE
UI: can't go back (easily) from Reddit page

### ISSUE THREAD

**Issue by tbm** [longjiang/zerotohero-nuxt#4]
Going back from the "Reddit posts" page isn't easy.

Reproduce:

Go to https://www.panlingo.org/en/sw/

Click on Reddit

This will open https://www.panlingo.org/en/sw/articles/reddit/

This will redirect to https://www.panlingo.org/en/sw/articles/reddit/list

Now if I click the "Back" button in my browser, it doesn't go back to the Swahili overview page, but it goes back to https://www.panlingo.org/en/sw/articles/reddit/ which against redirects to https://www.panlingo.org/en/sw/articles/reddit/list leaving me where I was before pressing the back button.

So the only way to go back is to click on back 2 times.  I think that's not ideal.

**Comment by longjiang** [comment]
Fixed with cf3f1bbd1b7dc1c2b9739faec174991b958d02bd
